import { Scale, Building2, Activity, Truck } from "lucide-react";
import type { DomainBlueprintConfig, DomainId } from "./types";

export const SHOWCASE_DOMAINS: Record<DomainId, DomainBlueprintConfig> = {
  "legal-os": {
    id: "legal-os",
    name: "Legal OS",
    category: "LITIGATION & PRACTICE TELEMETRY",
    tagline:
      "Eliminate unbilled partner hours and establish cryptographic audit trails for IOLTA trust escrow.",
    targetAudience: "Multi-Partner Law Firms & Complex Commercial Litigation",
    icon: Scale,
    metrics: {
      cycleReductionPercent: 93,
      baselineTurnaround: "4.2 days",
      ojixTurnaround: "18 mins",
      monthlyMarginLiftBase: 32400,
      baselineMonthlyLeak: 18400,
      complianceStandard: "100% Bar Compliant",
      baselineAuditRisk: "Severe State Bar Liability",
      architectureMode: "Event-Sourced ACID",
      baselineArchitecture: "Ad-Hoc Spreadsheets",
    },
    operationalBottlenecks: [
      "14 unlinked Excel workbooks across practice groups with divergent party data",
      "WhatsApp partner chats dispatching urgent court motions with zero read receipt audit",
      "Manual end-of-month trust account reconciliation creating severe bar liability",
    ],
    engineeredSolutions: [
      "Automated e-filing docket webhook ingestion with sub-second party indexing",
      "Relational conflict check evaluating 1,400+ adverse entities in real time",
      "Double-entry cryptographic ledger posting directly to escrow upon judicial validation",
    ],
    nodes: [
      {
        id: "l1",
        step: "01",
        name: "Court Docket Ingestion",
        type: "trigger",
        baselineStatus: "Manual clerk scanning · 6hr lag",
        ojixStatus: "Direct e-filing API · Webhook latency 14ms",
        latency: { baseline: "6 hrs", ojix: "14ms" },
        payloadSnippet: JSON.stringify(
          {
            docket_id: "2026-CV-88219",
            court: "Superior Court Div 4",
            filing_type: "Motion for Summary Judgment",
            status: "INGESTED_VERIFIED",
          },
          null,
          2,
        ),
        description: "Direct court clerk API parsing and normalization",
        telemetry: { latency: "14ms", protocol: "REST Webhook" },
      },
      {
        id: "l2",
        step: "02",
        name: "Entity Conflict Gate",
        type: "gate",
        baselineStatus: "Memory & sticky notes · High liability",
        ojixStatus: "Relational entity graph check · 0 false-negatives",
        exceptionStatus: "Adverse conflict detected · Disbursement locked",
        latency: { baseline: "72 hrs", ojix: "140ms" },
        payloadSnippet: JSON.stringify(
          {
            conflict_check: "PASS",
            entity_nodes_evaluated: 1420,
            adverse_parties_detected: 0,
            audit_hash: "0x8f2a41d9e2b109c391",
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            docket_id: "2026-CV-88219",
            conflict_check: "EXCEPTION_DETECTED",
            entity_nodes_evaluated: 1420,
            adverse_parties_detected: 1,
            adverse_match_record: {
              entity_name: "Apex Holdings LLC",
              prior_matter: "MAT-7819 (Cross-Licensing Arbitration)",
              rule_flag: "ABA_MODEL_RULE_1.9",
              screening_protocol: "MANDATORY_ETHICAL_WALL",
            },
            disbursement_lock: true,
            audit_hash: "0x7c91fa208b04e412",
          },
          null,
          2,
        ),
        description: "Zero false-negative cross-check evaluating 1,400+ entities",
        telemetry: { latency: "140ms", protocol: "Graph Relational Traversal" },
      },
      {
        id: "l3",
        step: "03",
        name: "Statutory Deadline Rule",
        type: "rule",
        baselineStatus: "Manual desk calendar entry · Missed dates",
        ojixStatus: "Jurisdiction rule engine · Automated calendaring",
        latency: { baseline: "4 hrs", ojix: "22ms" },
        payloadSnippet: JSON.stringify(
          {
            rule_jurisdiction: "CAL_CIV_PRO_437c",
            response_due_date: "2026-11-14T17:00:00Z",
            attorney_calendar_synced: true,
          },
          null,
          2,
        ),
        description: "Jurisdiction-calibrated calendar calculation engine",
        telemetry: { latency: "22ms", protocol: "Rules Evaluator" },
      },
      {
        id: "l4",
        step: "04",
        name: "IOLTA Escrow Ledger",
        type: "ledger",
        baselineStatus: "End-of-month manual reconciliation backlog",
        ojixStatus: "Real-time double-entry escrow post",
        exceptionStatus: "Disbursement locked ($0.00) · Audit flagged",
        latency: { baseline: "30 days", ojix: "12ms" },
        payloadSnippet: JSON.stringify(
          {
            matter_id: "MAT-9041",
            trust_disbursement: "$4,500.00",
            reconciled_balance: "$48,250.00",
            audit_trail: "IMMUTABLE_LOGGED",
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            matter_id: "MAT-9041",
            trust_disbursement: "$0.00 (LOCKED)",
            reconciled_balance: "$48,250.00",
            escrow_lock_reason: "ETHICAL_WALL_ACTIVE",
            audit_trail: "EXCEPTION_LOGGED",
          },
          null,
          2,
        ),
        description: "ACID immutable cryptographic double-entry commit",
        telemetry: { latency: "12ms", protocol: "PostgreSQL ACID Lock" },
      },
    ],
    stateToggles: [
      {
        id: "legal_toggle_conflict",
        label: "Simulate Adverse Entity Conflict",
        description:
          "Flags adverse party hit in relational entity graph, freezing escrow disbursement.",
        type: "switch",
        defaultValue: false,
        impactSummary: "Breaches Stage 02 Conflict Gate and locks Stage 04 IOLTA disbursement.",
        mutatedNodeId: "l2",
      },
      {
        id: "legal_toggle_protocol",
        label: "Filing Schedule Protocol",
        description:
          "Switch between standard statutory calendaring and emergency ex parte 24-hr STAT.",
        type: "segmented",
        defaultValue: "standard",
        options: [
          { value: "standard", label: "Standard 28-Day" },
          { value: "ex_parte", label: "Ex Parte 24-Hr STAT" },
        ],
        impactSummary:
          "Accelerates Stage 03 response window to emergency 24-hour statutory cutoff.",
        mutatedNodeId: "l3",
      },
    ],
  },
  "industrial-erp": {
    id: "industrial-erp",
    name: "Industrial ERP",
    category: "DISCRETE MANUFACTURING & SHOP-FLOOR OPS",
    tagline:
      "Replace printed clipboards and WhatsApp machine routing with real-time CNC telemetry.",
    targetAudience: "Industrial Mid-Market & Multi-Facility Precision Manufacturing",
    icon: Building2,
    metrics: {
      cycleReductionPercent: 98,
      baselineTurnaround: "48 hrs",
      ojixTurnaround: "3 mins",
      monthlyMarginLiftBase: 46800,
      baselineMonthlyLeak: 24200,
      complianceStandard: "ISO 9001 Traceable",
      baselineAuditRisk: "Zero Heat-Lot Serialization",
      architectureMode: "Real-Time Spindle Telemetry",
      baselineArchitecture: "Paper Clipboards",
    },
    operationalBottlenecks: [
      "Job traveler clipboards lost between CNC cutting cells and quality control bays",
      "WhatsApp supervisor channels used to notify heat-treat subcontractors with no audit log",
      "End-of-month manual BOM scrap reconciliation hiding thousands in raw bar-stock loss",
    ],
    engineeredSolutions: [
      "Sub-second barcode scan dispatching digital travelers directly to Haas & Mazak CNC cells",
      "Direct laser-etched heat-lot serialization linked immutably to mill test certifications",
      "Automated PO 3-way match committing subcontractor invoices immediately to general ledger",
    ],
    nodes: [
      {
        id: "e1",
        step: "01",
        name: "Work Order Trigger",
        type: "trigger",
        baselineStatus: "Paper clipboard traveler · Unmonitored",
        ojixStatus: "ERP job queue event · Barcode scan trigger",
        latency: { baseline: "4 hrs", ojix: "8ms" },
        payloadSnippet: JSON.stringify(
          {
            wo_id: "WO-2026-9042",
            facility_id: "PLANT-DETROIT-02",
            batch_quantity: 480,
            bom_rev: "REV_D_APPROVED",
          },
          null,
          2,
        ),
        description: "Barcode/RFID queue dispatch with machine spindle telemetry",
        telemetry: { latency: "8ms", protocol: "RFID / OPC-UA Ingest" },
      },
      {
        id: "e2",
        step: "02",
        name: "Tooling & Heat Gate",
        type: "gate",
        baselineStatus: "Visual check · Frequent stockout stalls",
        ojixStatus: "Automated warehouse RFID reserve check",
        exceptionStatus: "Wear > 0.0025mm · Spindle lockout active",
        latency: { baseline: "24 hrs", ojix: "32ms" },
        payloadSnippet: JSON.stringify(
          {
            alloy_spec: "TITANIUM-6AL-4V",
            heat_lot_verified: true,
            tooling_wear_tolerance: "0.0018mm (PASS)",
            allocated: true,
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            wo_id: "WO-2026-9042",
            alloy_spec: "TITANIUM-6AL-4V",
            heat_lot_verified: true,
            tooling_wear_tolerance: "0.0031mm (EXCEEDED > 0.0025mm)",
            spindle_interlock: "HARDWARE_LOCKED",
            mitigation_action: "HALT_CELL_04_DISPATCH_TOOL_CRIB",
            reroute_cell_assigned: "CNC-5AXIS-07",
            scrap_prevented_units: 480,
            audit_trail: "ISO_9001_CAPA_AUTO_POSTED",
          },
          null,
          2,
        ),
        description: "Titanium heat-lot and spindle wear verification before release",
        telemetry: { latency: "32ms", protocol: "CNC Spindle Sensor Mesh" },
      },
      {
        id: "e3",
        step: "03",
        name: "CNC Dynamic Routing",
        type: "rule",
        baselineStatus: "Whiteboard schedule · Operator phone calls",
        ojixStatus: "Machine telemetry load balancer",
        latency: { baseline: "6 hrs", ojix: "45ms" },
        payloadSnippet: JSON.stringify(
          {
            target_cell: "CNC-5AXIS-04",
            feed_rate_profile: "OPT_CYCLE_48s",
            spindle_hours_remaining: 342,
            dispatch_state: "ACTIVE",
          },
          null,
          2,
        ),
        description: "Multi-axis cell telemetry and load balancing engine",
        telemetry: { latency: "45ms", protocol: "Heuristic Dynamic Scheduler" },
      },
      {
        id: "e4",
        step: "04",
        name: "3-Way Match Ledger",
        type: "ledger",
        baselineStatus: "Accounts payable PDF email backlog",
        ojixStatus: "Instant ERP accounts payable ledger post",
        latency: { baseline: "18 days", ojix: "120ms" },
        payloadSnippet: JSON.stringify(
          {
            po_match_result: "EXACT_TOLERANCE_0_00",
            invoice_authorized: "$38,400.00",
            general_ledger_posted: true,
            reconciliation_time: "120ms",
          },
          null,
          2,
        ),
        description: "Automated PO 3-way match committed directly to GL",
        telemetry: { latency: "120ms", protocol: "ERP GL Double-Entry Commit" },
      },
    ],
    stateToggles: [
      {
        id: "erp_toggle_tooling",
        label: "Simulate Tool Wear Excursion (> 0.0025mm)",
        description:
          "Exceeds tool wear threshold to 0.0031mm, triggering automatic spindle hardware lockout and cell reroute.",
        type: "switch",
        defaultValue: false,
        impactSummary:
          "Halts Cell 04, protects 480 titanium billets from scrap, auto-reroutes to Cell 07.",
        mutatedNodeId: "e2",
      },
      {
        id: "erp_toggle_match_mode",
        label: "PO 3-Way Match Verification Mode",
        description:
          "Toggle between strict 0.00% exact invoice matching and fast-track 2.0% variance tolerance.",
        type: "segmented",
        defaultValue: "strict",
        options: [
          { value: "strict", label: "Strict 0% Variance" },
          { value: "fast_track", label: "Fast-Track 2% Tolerance" },
        ],
        impactSummary:
          "Captures early vendor discount and accelerates GL commit under SOX compliance.",
        mutatedNodeId: "e4",
      },
    ],
  },
  "clinical-logistics": {
    id: "clinical-logistics",
    name: "Clinical Logistics",
    category: "COLD-CHAIN & SPECIMEN CHAIN-OF-CUSTODY",
    tagline: "Sub-second BLE temperature telemetry guaranteeing strict CAP/CLIA compliance.",
    targetAudience: "Regional Pathology Labs & Diagnostic Healthcare Networks",
    icon: Activity,
    metrics: {
      cycleReductionPercent: 89,
      baselineTurnaround: "6.5 hrs",
      ojixTurnaround: "42 mins",
      monthlyMarginLiftBase: 28500,
      baselineMonthlyLeak: 16200,
      complianceStandard: "CAP / CLIA Certified",
      baselineAuditRisk: "12% Redraw Rate (Cold Degradation)",
      architectureMode: "BLE Cold-Chain Sync",
      baselineArchitecture: "Paper Courier Logs",
    },
    operationalBottlenecks: [
      "Personal courier phones coordinating STAT biohazard pickups with zero timestamp logging",
      "Unmonitored dry ice coolers leading to 12% specimen redraw rates on sensitive blood assays",
      "Manual sign-in sheets at receiving labs violating CAP/CLIA digital chain-of-custody rules",
    ],
    engineeredSolutions: [
      "Hardware-linked BLE data loggers broadcasting temperature telemetry every 250 milliseconds",
      "Algorithmic SLA routing dynamic courier dispatch based on traffic and specimen expiration",
      "NFC cryptographically signed custody transfers committing immediately to LIMS analyzer queues",
    ],
    nodes: [
      {
        id: "c1",
        step: "01",
        name: "Pickup Accession",
        type: "trigger",
        baselineStatus: "Clinic phone call to courier personal mobile",
        ojixStatus: "LIMS accessioning barcode generation",
        latency: { baseline: "45 mins", ojix: "12ms" },
        payloadSnippet: JSON.stringify(
          {
            accession_id: "SPEC-2026-X810",
            specimen_type: "WHOLE_BLOOD_EDTA",
            storage_protocol: "COLD_CHAIN_4C",
            clinic_id: "CLINIC-OAK-09",
          },
          null,
          2,
        ),
        description: "Automated LIMS barcode accessioning and digital custody tokens",
        telemetry: { latency: "12ms", protocol: "HL7 / FHIR Ingestion" },
      },
      {
        id: "c2",
        step: "02",
        name: "Thermal Guard Gate",
        type: "gate",
        baselineStatus: "Passive ice pack · Untracked degradation",
        ojixStatus: "Real-time BLE temperature sensor validation",
        exceptionStatus: "9.2°C thermal spike · Quarantine protocol active",
        latency: { baseline: "3.5 hrs", ojix: "450ms" },
        payloadSnippet: JSON.stringify(
          {
            current_temp: "3.8°C",
            threshold_window: "[2.0°C - 8.0°C]",
            excursion_seconds: 0,
            tamper_seal_intact: true,
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            accession_id: "SPEC-2026-X810",
            storage_protocol: "COLD_CHAIN_2C_TO_8C",
            current_temp: "9.2°C",
            temp_delta: "+1.2°C ABOVE THRESHOLD",
            excursion_duration_seconds: 142,
            tamper_seal_intact: true,
            telemetry_source: "BLE-LOG-4491-CRYOSYNC",
            quarantine_action: "AUTO_LOCK_SPECIMEN_NOTIFY_LIMS",
            clia_compliance_state: "QUARANTINED_PENDING_PHLEBOTOMY_REDRAW",
          },
          null,
          2,
        ),
        description: "Continuous BLE temperature monitoring within 2°C–8°C threshold",
        telemetry: { latency: "450ms", protocol: "BLE Beacon Telemetry" },
      },
      {
        id: "c3",
        step: "03",
        name: "Dynamic Courier Route Optimization",
        type: "rule",
        baselineStatus: "Driver memory · Traffic delays · Lost vials",
        ojixStatus: "SLA-constrained shortest-path dispatch",
        latency: { baseline: "2.5 hrs", ojix: "85ms" },
        payloadSnippet: JSON.stringify(
          {
            assigned_courier: "CR-04 (Certified Courier)",
            eta_central_lab: "38 mins (SLA: 60 mins)",
            traffic_penalty: "ZERO_DELAY",
            priority: "HIGH_STAT",
          },
          null,
          2,
        ),
        description: "STAT emergency queue priority with dynamic shortest-path routing",
        telemetry: { latency: "85ms", protocol: "Real-Time Telematics Route Engine" },
      },
      {
        id: "c4",
        step: "04",
        name: "LIMS Custody Ledger",
        type: "ledger",
        baselineStatus: "Illegible ballpoint signature on clipboard",
        ojixStatus: "Cryptographic digital handover & LIMS commit",
        exceptionStatus: "Quarantine hold rejected · Phlebotomy redraw triggered",
        latency: { baseline: "1 hr", ojix: "24ms" },
        payloadSnippet: JSON.stringify(
          {
            receiver_staff_id: "MED-TECH-481",
            sha256_custody_hash: "0x5a18c903de92bbfa71",
            lims_status: "COMMITTED_IN_ANALYZER",
            audit_verifiable: true,
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            receiver_staff_id: "MED-TECH-481",
            sha256_custody_hash: "0x5a18c903de92bbfa71",
            lims_status: "QUARANTINE_HOLD_REJECTED",
            redraw_order_id: "REDRAW-AUTO-9912",
            audit_verifiable: true,
          },
          null,
          2,
        ),
        description: "Cryptographic custody handover committed directly to analyzer database",
        telemetry: { latency: "24ms", protocol: "NFC Cryptographic Ledger Commit" },
      },
    ],
    stateToggles: [
      {
        id: "clinical_toggle_excursion",
        label: "Simulate Cold-Chain Thermal Excursion",
        description:
          "Spikes telemetry temperature to 9.2°C, breaching the 2°C–8°C window and triggering automated LIMS quarantine.",
        type: "switch",
        defaultValue: false,
        impactSummary:
          "Enforces CAP 14.2 excursion protocol and halts specimen processing before false diagnostic reporting.",
        mutatedNodeId: "c2",
      },
      {
        id: "clinical_toggle_route_mode",
        label: "Courier Dispatch Route Mode",
        description:
          "Select between routine multi-stop batch route and STAT emergency solo priority dispatch.",
        type: "segmented",
        defaultValue: "routine",
        options: [
          { value: "routine", label: "Routine Multi-Stop" },
          { value: "stat_emergency", label: "STAT Emergency Solo" },
        ],
        impactSummary:
          "Drops lab turnaround from 42 mins to 18 mins via emergency HOV corridor routing.",
        mutatedNodeId: "c3",
      },
    ],
  },
  "supply-chain-nexus": {
    id: "supply-chain-nexus",
    name: "Supply Chain",
    category: "MULTI-NODE FREIGHT & INVENTORY LEDGER",
    tagline:
      "Automate carrier waterfalls and stop detention fee leakage across distribution nodes.",
    targetAudience: "High-Throughput Distribution Centers & Freight Logistics Brokers",
    icon: Truck,
    metrics: {
      cycleReductionPercent: 98,
      baselineTurnaround: "12 hrs",
      ojixTurnaround: "8 mins",
      monthlyMarginLiftBase: 54200,
      baselineMonthlyLeak: 31800,
      complianceStandard: "100% Carrier Verified",
      baselineAuditRisk: "Unverified Detentions & Expired Policies",
      architectureMode: "Multi-Node Distributed Lock",
      baselineArchitecture: "Shared 40MB Spreadsheets",
    },
    operationalBottlenecks: [
      "Freight brokers booking spot trucks over WhatsApp with unverified cargo insurance certificates",
      "Carriers invoicing false detention fees without verifiable GPS dock entry/exit timestamps",
      "ERP inventory quantities desynchronized across three 3PL warehouses causing stockouts",
    ],
    engineeredSolutions: [
      "Automated FMCSA API insurance and safety rating verification prior to carrier tender release",
      "Geofenced cellular telematics auto-verifying driver arrival, loading dwell, and departure times",
      "Distributed multi-facility inventory ledger with atomic stock decrement across warehouses",
    ],
    nodes: [
      {
        id: "s1",
        step: "01",
        name: "EDI 850 Release",
        type: "trigger",
        baselineStatus: "Customer PDF email manually copied to Excel",
        ojixStatus: "Automated EDI 850 ingestion & line validation",
        latency: { baseline: "3 hrs", ojix: "18ms" },
        payloadSnippet: JSON.stringify(
          {
            edi_order_id: "EDI-850-9921",
            sku_count: 28,
            pallets: 42,
            origin_hub: "HUB-CHICAGO-NORTH",
            dest_hub: "HUB-DALLAS-SOUTH",
          },
          null,
          2,
        ),
        description: "Automated EDI 850 line-item purchase order ingestion",
        telemetry: { latency: "18ms", protocol: "ANSI X12 EDI 850 Parser" },
      },
      {
        id: "s2",
        step: "02",
        name: "Carrier Authority Gate",
        type: "gate",
        baselineStatus: "Manual FMCSA website check once a month",
        ojixStatus: "Real-time FMCSA safety & insurance query",
        exceptionStatus: "DOT authority lapsed · Disqualified from tender",
        latency: { baseline: "48 hrs", ojix: "180ms" },
        payloadSnippet: JSON.stringify(
          {
            carrier_dot: "DOT-3891042",
            cargo_insurance: "$250,000 (ACTIVE)",
            safety_rating: "SATISFACTORY",
            status: "APPROVED_FOR_TENDER",
          },
          null,
          2,
        ),
        exceptionPayloadSnippet: JSON.stringify(
          {
            carrier_dot: "DOT-3891042",
            carrier_name: "Apex Intermodal Freight",
            cargo_insurance: "$0.00 (POLICY_LAPSED)",
            safety_rating: "CONDITIONAL_WARNING",
            status: "REJECTED_DISQUALIFIED",
            fmcsa_query_timestamp: "2026-10-06T01:10:00Z",
            waterfall_escalation: "DISPATCH_TIER_2_BACKUP",
            replacement_carrier: "CARRIER-SWIFT-ALLIANCE",
            audit_hash: "0x44fa91cc8812e9b0",
          },
          null,
          2,
        ),
        description: "Real-time FMCSA API registry verification for cargo and safety ratings",
        telemetry: { latency: "180ms", protocol: "FMCSA Registry Webhook" },
      },
      {
        id: "s3",
        step: "03",
        name: "Dynamic Freight Tender Engine",
        type: "rule",
        baselineStatus: "Manual WhatsApp group messages with 30 carriers",
        ojixStatus: "Algorithmic tiered waterfall carrier dispatch",
        latency: { baseline: "8 hrs", ojix: "420ms" },
        payloadSnippet: JSON.stringify(
          {
            contract_rate: "$2.14 / mile",
            spot_market_avoidance: "+$480.00 saved",
            tender_acceptance_seconds: 42,
            contract_assigned: true,
          },
          null,
          2,
        ),
        description: "Tiered waterfall contract tender dispatch preventing spot market surges",
        telemetry: { latency: "420ms", protocol: "Cascading Waterfall Dispatch" },
      },
      {
        id: "s4",
        step: "04",
        name: "WMS Inventory Ledger",
        type: "ledger",
        baselineStatus: "Nightly batch CSV sync with frequent file corruption",
        ojixStatus: "Sub-second multi-warehouse inventory commit",
        latency: { baseline: "6.5 hrs", ojix: "18ms" },
        payloadSnippet: JSON.stringify(
          {
            allocated_wms_stock: 42,
            available_to_promise: 184,
            ledger_commit_latency: "18ms",
            zero_phantom_inventory: true,
          },
          null,
          2,
        ),
        description:
          "Multi-warehouse distributed ACID inventory allocation with zero phantom stock",
        telemetry: { latency: "18ms", protocol: "Distributed Consensus Multi-Lock" },
      },
    ],
    stateToggles: [
      {
        id: "supply_toggle_carrier_lapse",
        label: "Simulate FMCSA Carrier Insurance Revocation",
        description:
          "Simulate sudden policy lapse on primary carrier, triggering automatic rejection and immediate Tier-2 backup cascade.",
        type: "switch",
        defaultValue: false,
        impactSummary:
          "Prevents illegal non-insured freight assignment; waterfall transfers load to Carrier-Swift-Alliance.",
        mutatedNodeId: "s2",
      },
      {
        id: "supply_toggle_audit_protocol",
        label: "Loading Dock Dwell Audit Protocol",
        description:
          "Compare automated geofence GPS dwell telemetry against driver manual detention billing claim.",
        type: "segmented",
        defaultValue: "geofence",
        options: [
          { value: "geofence", label: "Geofence GPS Audit" },
          { value: "manual", label: "Manual Claim" },
        ],
        impactSummary:
          "Eradicates phantom detention invoices ($175 saved) by cross-referencing RFID geofence ingress timestamps.",
        mutatedNodeId: "s4",
      },
    ],
  },
};
